// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.5
// source: common.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNKNOWN               MessageType = 0
	MessageType_REGISTER_REQ          MessageType = 1
	MessageType_REGISTER_RESP         MessageType = 2
	MessageType_HEARTBEAT_REQ         MessageType = 3
	MessageType_HEARTBEAT_RESP        MessageType = 4
	MessageType_DISCONNECT_REQ        MessageType = 5
	MessageType_TASK_DISPATCH_REQ     MessageType = 6
	MessageType_TASK_DISPATCH_RESP    MessageType = 7
	MessageType_CONTAINER_STATUS_REQ  MessageType = 8
	MessageType_CONTAINER_STATUS_RESP MessageType = 9
	MessageType_CONTAINER_LOGS_REQ    MessageType = 10
	MessageType_CONTAINER_LOGS_RESP   MessageType = 11
	MessageType_ARTIFACT_REQ          MessageType = 12
	MessageType_ARTIFACT_DATA         MessageType = 13
	MessageType_ARTIFACT_ACK          MessageType = 14
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "REGISTER_REQ",
		2:  "REGISTER_RESP",
		3:  "HEARTBEAT_REQ",
		4:  "HEARTBEAT_RESP",
		5:  "DISCONNECT_REQ",
		6:  "TASK_DISPATCH_REQ",
		7:  "TASK_DISPATCH_RESP",
		8:  "CONTAINER_STATUS_REQ",
		9:  "CONTAINER_STATUS_RESP",
		10: "CONTAINER_LOGS_REQ",
		11: "CONTAINER_LOGS_RESP",
		12: "ARTIFACT_REQ",
		13: "ARTIFACT_DATA",
		14: "ARTIFACT_ACK",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":               0,
		"REGISTER_REQ":          1,
		"REGISTER_RESP":         2,
		"HEARTBEAT_REQ":         3,
		"HEARTBEAT_RESP":        4,
		"DISCONNECT_REQ":        5,
		"TASK_DISPATCH_REQ":     6,
		"TASK_DISPATCH_RESP":    7,
		"CONTAINER_STATUS_REQ":  8,
		"CONTAINER_STATUS_RESP": 9,
		"CONTAINER_LOGS_REQ":    10,
		"CONTAINER_LOGS_RESP":   11,
		"ARTIFACT_REQ":          12,
		"ARTIFACT_DATA":         13,
		"ARTIFACT_ACK":          14,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\rnexa_protocol*\xc6\x02\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fREGISTER_REQ\x10\x01\x12\x11\n" +
	"\rREGISTER_RESP\x10\x02\x12\x11\n" +
	"\rHEARTBEAT_REQ\x10\x03\x12\x12\n" +
	"\x0eHEARTBEAT_RESP\x10\x04\x12\x12\n" +
	"\x0eDISCONNECT_REQ\x10\x05\x12\x15\n" +
	"\x11TASK_DISPATCH_REQ\x10\x06\x12\x16\n" +
	"\x12TASK_DISPATCH_RESP\x10\a\x12\x18\n" +
	"\x14CONTAINER_STATUS_REQ\x10\b\x12\x19\n" +
	"\x15CONTAINER_STATUS_RESP\x10\t\x12\x16\n" +
	"\x12CONTAINER_LOGS_REQ\x10\n" +
	"\x12\x17\n" +
	"\x13CONTAINER_LOGS_RESP\x10\v\x12\x10\n" +
	"\fARTIFACT_REQ\x10\f\x12\x11\n" +
	"\rARTIFACT_DATA\x10\r\x12\x10\n" +
	"\fARTIFACT_ACK\x10\x0eBF\n" +
	"\x11com.nexa.protocolZ1github.com/leehaohaohao/nexa-protocol/go/messagesb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_goTypes = []any{
	(MessageType)(0), // 0: nexa_protocol.MessageType
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
