// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: disconnect.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_disconnect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_disconnect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_disconnect_proto_rawDescGZIP(), []int{0}
}

func (x *DisconnectRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *DisconnectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_disconnect_proto protoreflect.FileDescriptor

const file_disconnect_proto_rawDesc = "" +
	"\n" +
	"\x10disconnect.proto\x12\rnexa_protocol\"H\n" +
	"\x11DisconnectRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonB3Z1github.com/leehaohaohao/nexa-protocol/go/messagesb\x06proto3"

var (
	file_disconnect_proto_rawDescOnce sync.Once
	file_disconnect_proto_rawDescData []byte
)

func file_disconnect_proto_rawDescGZIP() []byte {
	file_disconnect_proto_rawDescOnce.Do(func() {
		file_disconnect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_disconnect_proto_rawDesc), len(file_disconnect_proto_rawDesc)))
	})
	return file_disconnect_proto_rawDescData
}

var file_disconnect_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_disconnect_proto_goTypes = []any{
	(*DisconnectRequest)(nil), // 0: nexa_protocol.DisconnectRequest
}
var file_disconnect_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_disconnect_proto_init() }
func file_disconnect_proto_init() {
	if File_disconnect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_disconnect_proto_rawDesc), len(file_disconnect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_disconnect_proto_goTypes,
		DependencyIndexes: file_disconnect_proto_depIdxs,
		MessageInfos:      file_disconnect_proto_msgTypes,
	}.Build()
	File_disconnect_proto = out.File
	file_disconnect_proto_goTypes = nil
	file_disconnect_proto_depIdxs = nil
}
