// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.5
// source: query.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	DeployName    string                 `protobuf:"bytes,2,opt,name=deploy_name,json=deployName,proto3" json:"deploy_name,omitempty"`
	VolumeDir     string                 `protobuf:"bytes,3,opt,name=volume_dir,json=volumeDir,proto3" json:"volume_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatusRequest) Reset() {
	*x = ContainerStatusRequest{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatusRequest) ProtoMessage() {}

func (x *ContainerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatusRequest.ProtoReflect.Descriptor instead.
func (*ContainerStatusRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerStatusRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ContainerStatusRequest) GetDeployName() string {
	if x != nil {
		return x.DeployName
	}
	return ""
}

func (x *ContainerStatusRequest) GetVolumeDir() string {
	if x != nil {
		return x.VolumeDir
	}
	return ""
}

type ContainerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // running / stopped / restarting / exited...
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatusResponse) Reset() {
	*x = ContainerStatusResponse{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatusResponse) ProtoMessage() {}

func (x *ContainerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatusResponse.ProtoReflect.Descriptor instead.
func (*ContainerStatusResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerStatusResponse) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *ContainerStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ContainerStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerStatusResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ContainerStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ContainerLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	DeployName    string                 `protobuf:"bytes,2,opt,name=deploy_name,json=deployName,proto3" json:"deploy_name,omitempty"`
	VolumeDir     string                 `protobuf:"bytes,3,opt,name=volume_dir,json=volumeDir,proto3" json:"volume_dir,omitempty"`
	Tail          int32                  `protobuf:"varint,4,opt,name=tail,proto3" json:"tail,omitempty"`  // 尾部行数
	Since         string                 `protobuf:"bytes,5,opt,name=since,proto3" json:"since,omitempty"` // 可选
	Until         string                 `protobuf:"bytes,6,opt,name=until,proto3" json:"until,omitempty"` // 可选
	Timestamps    bool                   `protobuf:"varint,7,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerLogsRequest) Reset() {
	*x = ContainerLogsRequest{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogsRequest) ProtoMessage() {}

func (x *ContainerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogsRequest.ProtoReflect.Descriptor instead.
func (*ContainerLogsRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerLogsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ContainerLogsRequest) GetDeployName() string {
	if x != nil {
		return x.DeployName
	}
	return ""
}

func (x *ContainerLogsRequest) GetVolumeDir() string {
	if x != nil {
		return x.VolumeDir
	}
	return ""
}

func (x *ContainerLogsRequest) GetTail() int32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

func (x *ContainerLogsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *ContainerLogsRequest) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *ContainerLogsRequest) GetTimestamps() bool {
	if x != nil {
		return x.Timestamps
	}
	return false
}

type ContainerLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerLogsResponse) Reset() {
	*x = ContainerLogsResponse{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogsResponse) ProtoMessage() {}

func (x *ContainerLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogsResponse.ProtoReflect.Descriptor instead.
func (*ContainerLogsResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerLogsResponse) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *ContainerLogsResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ContainerLogsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\rnexa_protocol\"w\n" +
	"\x16ContainerStatusRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vdeploy_name\x18\x02 \x01(\tR\n" +
	"deployName\x12\x1d\n" +
	"\n" +
	"volume_dir\x18\x03 \x01(\tR\tvolumeDir\"\x96\x01\n" +
	"\x17ContainerStatusResponse\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xd5\x01\n" +
	"\x14ContainerLogsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vdeploy_name\x18\x02 \x01(\tR\n" +
	"deployName\x12\x1d\n" +
	"\n" +
	"volume_dir\x18\x03 \x01(\tR\tvolumeDir\x12\x12\n" +
	"\x04tail\x18\x04 \x01(\x05R\x04tail\x12\x14\n" +
	"\x05since\x18\x05 \x01(\tR\x05since\x12\x14\n" +
	"\x05until\x18\x06 \x01(\tR\x05until\x12\x1e\n" +
	"\n" +
	"timestamps\x18\a \x01(\bR\n" +
	"timestamps\"d\n" +
	"\x15ContainerLogsResponse\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorBF\n" +
	"\x11com.nexa.protocolZ1github.com/leehaohaohao/nexa-protocol/go/messagesb\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_query_proto_goTypes = []any{
	(*ContainerStatusRequest)(nil),  // 0: nexa_protocol.ContainerStatusRequest
	(*ContainerStatusResponse)(nil), // 1: nexa_protocol.ContainerStatusResponse
	(*ContainerLogsRequest)(nil),    // 2: nexa_protocol.ContainerLogsRequest
	(*ContainerLogsResponse)(nil),   // 3: nexa_protocol.ContainerLogsResponse
}
var file_query_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
